name: flash-drought
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - dask
  - distributed
  - earthaccess
  - fastparquet
  - h5netcdf
  - ipykernel
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pyproj
  - rasterio
  - requests
  - tqdm
  - virtualizarr
  - xarray
